#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_H

#define LAND_WILD_COUNT       12
#define WATER_WILD_COUNT      5
#define ROCK_SMASH_WILD_COUNT 5
#define FISH_WILD_COUNT       10
#define HIDDEN_WILD_COUNT     3

#define ROCK_WILD_COUNT                     ROCK_SMASH_WILD_COUNT
#define FISHING_WILD_COUNT                  FISH_WILD_COUNT
#define NUM_LAND_MONS_ENCOUNTER_SLOTS       LAND_WILD_COUNT
#define NUM_WATER_MONS_ENCOUNTER_SLOTS      WATER_WILD_COUNT
#define NUM_ROCK_SMASH_MONS_ENCOUNTER_SLOTS ROCK_SMASH_WILD_COUNT
#define NUM_FISHING_MONS_ENCOUNTER_SLOTS    FISH_WILD_COUNT

#define NUM_ALTERING_CAVE_SETS   9
#define NUM_ALTERING_CAVE_TABLES 9
#define NUM_ALTERING_CAVE_SETS 9

// Land encounter chance thresholds
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_0 20
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_1 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_0 + 20)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_2 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_1 + 10)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_3 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_2 + 10)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_4 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_3 + 10)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_5 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_4 + 10)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_6 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_5 + 5)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_7 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_6 + 5)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_8 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_7 + 4)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_9 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_8 + 4)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_10 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_9 + 1)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_11 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_10 + 1)
#define ENCOUNTER_CHANCE_LAND_MONS_TOTAL (ENCOUNTER_CHANCE_LAND_MONS_SLOT_11)

// Water encounter chance thresholds
#define ENCOUNTER_CHANCE_WATER_MONS_SLOT_0 60
#define ENCOUNTER_CHANCE_WATER_MONS_SLOT_1 (ENCOUNTER_CHANCE_WATER_MONS_SLOT_0 + 30)
#define ENCOUNTER_CHANCE_WATER_MONS_SLOT_2 (ENCOUNTER_CHANCE_WATER_MONS_SLOT_1 + 5)
#define ENCOUNTER_CHANCE_WATER_MONS_SLOT_3 (ENCOUNTER_CHANCE_WATER_MONS_SLOT_2 + 4)
#define ENCOUNTER_CHANCE_WATER_MONS_SLOT_4 (ENCOUNTER_CHANCE_WATER_MONS_SLOT_3 + 1)
#define ENCOUNTER_CHANCE_WATER_MONS_TOTAL (ENCOUNTER_CHANCE_WATER_MONS_SLOT_4)

// Rock Smash encounter chance thresholds
#define ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_0 60
#define ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_1 (ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_0 + 30)
#define ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_2 (ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_1 + 5)
#define ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_3 (ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_2 + 4)
#define ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_4 (ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_3 + 1)
#define ENCOUNTER_CHANCE_ROCK_SMASH_MONS_TOTAL (ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_4)

#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_H